Repository ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-e1-proj-web-t2-daybyday, pull requests merged in 2024-06, with the labels that each got.

#10 Dbd 6 - button "logout" created
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/styles.css
Labels: ready for review

#11 DBD-4 --> validation for password and creation + validation for email too
  src/pages/login/login.html
  src/pages/login/loginScript.js
  src/pages/register/register.html
  src/pages/register/registerScript.js
Labels: ready for review

#21 2 inputs and only one output plus email verification
  src/pages/login/login.html
  src/pages/login/loginScript.js
Labels: ready for review

#16 Translations of page
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/scripts.js
  src/pages/login/login.html
  src/pages/register/register.html
Labels: ready for review

#15 Dbd 4 + Others issues solveds
  src/index.css
  src/index.html
  src/script.js
Labels: ready for review

#27 alert on negative balance working only once
  src/pages/dashboard/dashboardscript.js
Labels: ready for review

#33 put a string on the carousel button
  src/index.html
Labels: ready for review

#37 Mudança da funcionalidade do botão logout
  src/pages/dashboard/dashboardscript.js
Labels: feature

#36 Pequenos Ajustes
  src/pages/dashboard/dashboard.css
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.js
  src/pages/dashboard/despesas.svg
  src/pages/dashboard/economias.svg
  src/pages/dashboard/receitas.svg
  src/pages/dashboard/saldo.svg
Labels: Code/ In progress
